# Generated by Django 4.0.6 on 2022-07-05 18:48

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("subtitle", models.CharField(blank=True, max_length=500)),
                ("hosted_by", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="podcasts/")),
                ("links", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("audio", models.FileField(blank=True, upload_to="episodes/")),
                ("image", models.ImageField(blank=True, upload_to="episodes/")),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.podcast"
                    ),
                ),
            ],
        ),
    ]
