# Generated by Django 4.0.6 on 2022-07-07 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribed_podcasts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
