# Generated by Django 4.0.6 on 2022-07-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="total_time",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
